// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgELLWa5P_0cyjodxOmuBhoTcpUnLcMCg',
    appId: '1:700364587110:web:d7d800c402a0d172146da7',
    messagingSenderId: '700364587110',
    projectId: 'checkpoint-test-d5beb',
    authDomain: 'checkpoint-test-d5beb.firebaseapp.com',
    databaseURL: 'https://checkpoint-test-d5beb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkpoint-test-d5beb.firebasestorage.app',
    measurementId: 'G-R2XCDW4X93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Jl6J_guWviPsyMQ-3LwRalBPbZ9-j2U',
    appId: '1:700364587110:android:fcdf00ca0603dcbd146da7',
    messagingSenderId: '700364587110',
    projectId: 'checkpoint-test-d5beb',
    databaseURL: 'https://checkpoint-test-d5beb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkpoint-test-d5beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPG3tD3kqZLwOAG0n8WcA4quobB1e4LmI',
    appId: '1:700364587110:ios:bc83de74ca5dfde2146da7',
    messagingSenderId: '700364587110',
    projectId: 'checkpoint-test-d5beb',
    databaseURL: 'https://checkpoint-test-d5beb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkpoint-test-d5beb.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPG3tD3kqZLwOAG0n8WcA4quobB1e4LmI',
    appId: '1:700364587110:ios:bc83de74ca5dfde2146da7',
    messagingSenderId: '700364587110',
    projectId: 'checkpoint-test-d5beb',
    databaseURL: 'https://checkpoint-test-d5beb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkpoint-test-d5beb.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgELLWa5P_0cyjodxOmuBhoTcpUnLcMCg',
    appId: '1:700364587110:web:a4a7d3bd877ff5b2146da7',
    messagingSenderId: '700364587110',
    projectId: 'checkpoint-test-d5beb',
    authDomain: 'checkpoint-test-d5beb.firebaseapp.com',
    databaseURL: 'https://checkpoint-test-d5beb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkpoint-test-d5beb.firebasestorage.app',
    measurementId: 'G-MN5FVEF80L',
  );

}